get:
  summary: Returns a list of products
  description: List of products
  responses:
    '200':
      description: A JSON array of products
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: number
              price:
                type: number
              amount:
                type: number
              name:
                type: string
    default:
      description: Unexpected error
